##
## This file is part of the libopencm3 project.
##
## Copyright (C) 2022 Alwin Leerling <dna.leerling@gmail.com>
##
## This library is free software: you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with this library.  If not, see <http://www.gnu.org/licenses/>.
##

all:
	make -C fancyblink
	make -C timedblink
	make -C interruptblink
	make -C systickblink
	make -C pwmblink
	make -C controlledblink
	make -C serialblink

clean:

	make -C fancyblink clean
	make -C timedblink clean
	make -C interruptblink clean
	make -C systickblink clean
	make -C pwmblink clean
	make -C controlledblink clean
	make -C serialblink clean
